export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";

export const UPDATE_POSTS_REQUEST = "UPDATE_POSTS_REQUEST";
export const UPDATE_POSTS_SUCCESS = "UPDATE_POSTS_SUCCESS";
export const UPDATE_POSTS_FAILURE = "UPDATE_POSTS_FAILURE";
