export const REQUEST = "REQUEST"
export const FAILURE = "FAILURE"
export const HANDLE_ERROR = "HANDLE_ERROR"

export const BOOK_SEARCH_SUCCESS = "BOOK_SEARCH_SUCCESS"

export const GET_SELECTED_BOOK = "GET_SELECTED_BOOK"